### ISSUE TITLE
00 -- Brace Yourself -- Jorge Hernandez task list

### ISSUE THREAD

**Issue by jorgehjr84** [TheIronYard--Orlando/2015--SUMMER--FEE#2]
### Tasks:
- [X] [Create a Github account](https://github.com/signup)
- [X] Find and star [the class project](https://github.com/TheIronYard--Orlando/FEE--2015--SPRING)
- [x] Read [the Home page on the class wiki](https://github.com/TheIronYard--Orlando/2015--SUMMER--FEE/wiki)
- [x] [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/new)
  - [x] Named `00 -- Brace Yourself -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  - [x] With this checklist as the description
- [x] [Edit your Github profile](https://github.com/settings/profile) to provide:
  - [x] A picture, so I can recognize your face.
  - [x] Your full name, so I can recognize your name.
  - [x] A valid public email address, so I can contact you if I need to.
- [x] [Install Homebrew](http://brew.sh) on your Mac
  - [x] Open `Terminal.app`; Don't Panic.
  - [x] [Install Homebrew and the `brew` command](http://brew.sh/#install)
  - [x] Read [the Homebrew Wiki](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme) to learn more about Homebrew
- [x] Using the `brew` command, install the following packages:
  - [x] `zsh`
  - [x] `git`
  - [x] `hub`
  - [x] `node`
- [x] Add the output of the following commands as comments on your _WIP Issue_:
  - [x] `which zsh && zsh --version`
  - [x] `which git && git --version`
  - [x] `which hub && hub --version`
  - [x] `which node && node --version`
- [x] Install the following (bonus if you use `brew`):
  - [x] [Google Chrome](http://google.com/chrome)
  - [x] [Dash](http://kapeli.com/dash)
  - [x] [Slack](http://www.slack.com)
  - [x] [Atom](http://atom.io)
- [x] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  - [x] Add a link to your new Github repo as a comment on your _WIP Issue_
- [x] Create a new repository called `TIY-Assignments`
  - [x] Check the box to create an initial `README.md` file
  - [x] Select the `CC0` -- "Creative Commons" license for your work
  - [x] Add a link to your `TIY-Assignments` repo as a comment on your _WIP Issue_
- [x] [Complete the "Forking Projects" Github guide](https://guides.github.com/activities/forking/)
  - [x] Add a link to your `Fork-and-Spoon` repo as a comment on your _WIP Issue_
- [x] Install Prezto
  - [x] Find _and fork_ the Prezto project on Github; add a link as a comment on your _WIP Issue_
  - [x] Use the `hub` command to clone your fork into your home directory as `.zprezto`: `hub clone prezto .zprezto`
- [x] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
  - [x] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
  - [x] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)
### Deliverables:
- [x] _WIP Issue_
  - [x] named `00 -- Brace Yourself -- YOUR NAME`
  - [x] with description matching **Tasks**
- [x] A Github Profile with:
  - [x] Intelligible picture of yourself
  - [x] Your full name
  - [x] A valid email address
- [x] Comments on your _WIP Issue_ with output from
  - [x] `which zsh && zsh --version`
  - [x] `which git && git --version`
  - [x] `which hub && hub --version`
  - [x] `which node && node --version`
- [x] Comments on your _WIP Issue_ with links to your repos for
  - [x] `Hello-World`
  - [x] `TIY-Assignments`
  - [x] `Fork-and-Spoon`
  - [x] `prezto`

**Comment by al-the-x** [comment]
Looking good, but check the instructions and the example (#1) for how to _name_ your issue. ;)

**Comment by jorgehjr84** [comment]
/bin/zsh
'git help -a' and 'git help -g' lists available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
hub not found
node not found

**Comment by jorgehjr84** [comment]
https://github.com/jorgehjr84/hello-world.git

**Comment by jorgehjr84** [comment]
https://github.com/jorgehjr84/TIY-Assignments.git

**Comment by al-the-x** [comment]
Great work. Try researching how to install `hub` and `node` and get those working. You'll need those, too.

**Comment by jorgehjr84** [comment]
Thanks. I found out how to install them. I believe I did them correct.

/usr/local/bin/hub
usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [-c name=value] [--help]
           <command> [<args>]

/usr/local/bin/node

**Comment by jorgehjr84** [comment]
https://github.com/jorgehjr84/Spoon-Knife.git

**Comment by jorgehjr84** [comment]
https://github.com/jorgehjr84/prezto.git

**Comment by al-the-x** [comment]
Did you open a PR in the `Spoon-Knife` repo per the instructions in the "Forking Projects" guide?

**Comment by al-the-x** [comment]
Please review and close...
