### ISSUE TITLE
03 -- Todo CLI 1 -- Phillip Creglow

### ISSUE THREAD

**Issue by pcreglow** [TheIronYard--Orlando/2015--SUMMER--FEE#42]
- **Yak Shaving**
  - _WIP Issue_: `03 -- Todo CLI 1 -- YOUR NAME`
    - [x] link to PR in `USERNAME.github.io`
    - [x] link to PR in `TIY-Assignments`
  -  _WIP Branch_:
    - [x] `USERNAME.github.io:01--right-mindset`
    - [x] `TIY-Assignments:03--todo-cli-1`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `about/javascript.md`
      - `growth-vs-fixed-mindset.md`
    - `TIY-Assignments`
      - `todo.js`
- **The Right Mindset**
  - [x] commits in `growth-vs-fixed-mindset.md` towareds final draft
  - [x] link to open PR in `USERNAME.github.io`
- **Reading JavaScript**
  - [x] 2 more entries!
  - [x] 5 more entries!
  - [x] 10 more entries!
  - [x] `Array` literal with examples
  - [x] `length` with examples
  - [x] 2 `Array.prototype` methods!
- **TodoCLI and You!**
  - [x] created issues in `TIY-Assignments` for User Stories
  - [x] create branch named `03--todo-cli-1`
  - [x] committed and pushed `todo.js`
  - [x] opened PR _from_ `03--todo-cli-1` _to_ `master`
  - [x] 1 more passing test than in class!

**Comment by pcreglow** [comment]
TIY-Assignments PR

https://github.com/pcreglow/TIY-Assignments/pull/1

**Comment by pcreglow** [comment]
pcreglow.github.io PR

https://github.com/pcreglow/pcreglow.github.io/pull/2

**Comment by pcreglow** [comment]
New pcreglow.github.io PR - Progress on JS entries and Essay

https://github.com/pcreglow/pcreglow.github.io/pull/5

**Comment by al-the-x** [comment]
Little screwy here, but I get you. First week is just full of mistakes for everyone.

**Comment by al-the-x** [comment]
Honestly, weeks 2 hrough 12 are mostly full of mistakes, too.

**Comment by al-the-x** [comment]
Please review and close.
