### ISSUE TITLE
03 -- Todo CLI 1 -- Nick Pope

### ISSUE THREAD

**Issue by pope410211** [TheIronYard--Orlando/2015--SUMMER--FEE#43]
- [x] **Yak Shaving**
  - [x] _WIP Issue_: `03 -- Todo CLI 1 -- YOUR NAME`
    - [x] link to PR in `USERNAME.github.io`
    - [x] link to PR in `TIY-Assignments`
  -  [x] _WIP Branch_:
    - [X] `USERNAME.github.io:01--right-mindset`
    - [x] `TIY-Assignments:03--todo-cli-1`
  - [x] _WIP Files_:
    - [x] `USERNAME.github.io`
      - [x] `about/javascript.md`
      - [x] `growth-vs-fixed-mindset.md`
    - [x] `TIY-Assignments`
      - [x] `todo.js`
- [x] **The Right Mindset**
  - [x] commits in `growth-vs-fixed-mindset.md` towareds final draft
  - [x] link to open PR in `USERNAME.github.io`
- [ ] **Reading JavaScript**
  - [ ] 2 more entries!
  - [ ] 5 more entries!
  - [ ] 10 more entries!
  - [ ] `Array` literal with examples
  - [ ] `length` with examples
  - [ ] 2 `Array.prototype` methods!
- [ ] **TodoCLI and You!**
  - [x] created issues in `TIY-Assignments` for User Stories
  - [x] create branch named `03--todo-cli-1`
  - [x] committed and pushed `todo.js`
  - [x] opened PR _from_ `03--todo-cli-1` _to_ `master`
  - [ ] 1 more passing test than in class!

**Comment by pope410211** [comment]
[PR for TIY-ASSIGNMETS](https://github.com/pope410211/TIY-Assignments/pull/1)

**Comment by pope410211** [comment]
I was making attempts to use Atom to update 01--right-mindset and created a the following [**_PULL REQ._**](https://github.com/pope410211/pope410211.github.io/pull/10)

May Have accidentally deleted original made in web browser.
-N

**Comment by al-the-x** [comment]
Yeah, so I can see where you got sideways on this. I'll give you a mercy yellow.

**Comment by al-the-x** [comment]
Please review and close.
