### ISSUE TITLE
03 -- Todo CLI 1 -- JESSY RIORDAN

### ISSUE THREAD

**Issue by JessyRiordan** [TheIronYard--Orlando/2015--SUMMER--FEE#45]
- [x] **Yak Shaving**
  - _WIP Issue_: `03 -- Todo CLI 1 -- YOUR NAME`
    - [x] link to PR in `USERNAME.github.io`
    - [x] link to PR in `TIY-Assignments`
  -  _WIP Branch_:
    - [X] `USERNAME.github.io:01--right-mindset`
    - [x] `TIY-Assignments:03--todo-cli-1`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `about/javascript.md`
      - `growth-vs-fixed-mindset.md`
    - `TIY-Assignments`
      - `todo.js`
- **The Right Mindset**
  - [x] commits in `growth-vs-fixed-mindset.md` towareds final draft
  - [x] link to open PR in `USERNAME.github.io`
- **Reading JavaScript**
  - [ ] 2 more entries!
  - [ ] 5 more entries!
  - [ ] 10 more entries!
  - [ ] `Array` literal with examples
  - [ ] `length` with examples
  - [ ] 2 `Array.prototype` methods!
- **TodoCLI and You!**
  - [x] created issues in `TIY-Assignments` for User Stories
  - [x] create branch named `03--todo-cli-1`
  - [x] committed and pushed `todo.js`
  - [x] opened PR _from_ `03--todo-cli-1` _to_ `master`
  - [ ] 1 more passing test than in class!

**Comment by JessyRiordan** [comment]
https://github.com/JessyRiordan/jessyriordan.github.io/pull/1

**Comment by JessyRiordan** [comment]
https://github.com/JessyRiordan/TIY-Assignments/pull/1

**Comment by al-the-x** [comment]
Great User Stories, but where's my JavaScript tutorial? How will I ever learn?

**Comment by al-the-x** [comment]
Please review and close.

**Comment by JessyRiordan** [comment]
I am realizing now that I seriously need to update the JavaScript tutorial, for my benefit. Thanks :smile:
