### ISSUE TITLE
03--todo CLI1-- Jorge Hernandez

### ISSUE THREAD

**Issue by jorgehjr84** [TheIronYard--Orlando/2015--SUMMER--FEE#46]
- **Yak Shaving**
  - _WIP Issue_: `03 -- Todo CLI 1 -- YOUR NAME`
    - [x] link to PR in `USERNAME.github.io`
    - [ ] link to PR in `TIY-Assignments`
  -  _WIP Branch_:
    - [X] `USERNAME.github.io:01--right-mindset`
    - [x] `TIY-Assignments:03--todo-cli-1`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `about/javascript.md`
      - `growth-vs-fixed-mindset.md`
    - `TIY-Assignments`
      - `todo.js`
- **The Right Mindset**
  - [x] commits in `growth-vs-fixed-mindset.md` towareds final draft
  - [x] link to open PR in `USERNAME.github.io`
- **Reading JavaScript**
  - [x] 2 more entries!
  - [x] 5 more entries!
  - [x] 10 more entries!
  - [x] `Array` literal with examples
  - [x] `length` with examples
  - [x] 2 `Array.prototype` methods!
- **TodoCLI and You!**
  - [x] created issues in `TIY-Assignments` for User Stories
  - [x] create branch named `03--todo-cli-1`
  - [ ] committed and pushed `todo.js`
  - [ ] opened PR _from_ `03--todo-cli-1` _to_ `master`
  - [ ] 1 more passing test than in class!

**Comment by jorgehjr84** [comment]
https://github.com/jorgehjr84/TIY-Assignments/pull/7

**Comment by jorgehjr84** [comment]
https://github.com/jorgehjr84/jorgehjr84.github.io-/pull/5

**Comment by al-the-x** [comment]
Forgot to check off some boxes, buddy.

**Comment by al-the-x** [comment]
Looking good except for the links to your User Story issues.

**Comment by al-the-x** [comment]
Please review and close.
