### ISSUE TITLE
03 -- Todo CLI 1 -- Sean Joyal

### ISSUE THREAD

**Issue by sjoyal** [TheIronYard--Orlando/2015--SUMMER--FEE#48]
- **Yak Shaving**
  - _WIP Issue_: `03 -- Todo CLI 1 -- YOUR NAME`
    - [x] link to PR in `USERNAME.github.io`
    - [x] link to PR in `TIY-Assignments`
  -  _WIP Branch_:
    - [X] `USERNAME.github.io:01--right-mindset`
    - [x] `TIY-Assignments:03--todo-cli-1`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `about/javascript.md`
      - `growth-vs-fixed-mindset.md`
    - `TIY-Assignments`
      - [x] `todo.js`
- **The Right Mindset**
  - [x] commits in `growth-vs-fixed-mindset.md` towards final draft
  - [x] link to open PR in `USERNAME.github.io`
- **Reading JavaScript**
  - [x] 2 more entries!
  - [x] 5 more entries!
  - [x] 10 more entries!
  - [x] `Array` literal with examples
  - [x] `length` with examples
  - [x] 2 `Array.prototype` methods!
- **TodoCLI and You!**
  - [x] created issues in `TIY-Assignments` for User Stories
  - [x] create branch named `03--todo-cli-1`
  - [x] committed and pushed `todo.js`
  - [x] opened PR _from_ `03--todo-cli-1` _to_ `master`
  - [ ] 1 more passing test than in class!

**Comment by sjoyal** [comment]
https://github.com/sjoyal/sjoyal.github.io/pull/1

**Comment by sjoyal** [comment]
https://github.com/sjoyal/TIY-Assignments/pull/1

**Comment by al-the-x** [comment]
Please review and close.
