### ISSUE TITLE
00 -- Brace Yourself -- Kim Mattiko

### ISSUE THREAD

**Issue by kmattiko** [TheIronYard--Orlando/2015--SUMMER--FEE#6]
### Tasks:
- [X] [Create a Github account](https://github.com/signup)
- [X] Find and star [the class project](https://github.com/TheIronYard--Orlando/FEE--2015--SPRING)
- [X] Read [the Home page on the class wiki](https://github.com/TheIronYard--Orlando/2015--SUMMER--FEE/wiki)
- [X] [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/new)
  - [X] Named `00 -- Brace Yourself -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  - [X] With this checklist as the description
- [X] [Edit your Github profile](https://github.com/settings/profile) to provide:
  - [X] A picture, so I can recognize your face.
  - [X] Your full name, so I can recognize your name.
  - [X] A valid public email address, so I can contact you if I need to.
- [X] [Install Homebrew](http://brew.sh) on your Mac
  - [X] Open `Terminal.app`; Don't Panic.
  - [X] [Install Homebrew and the `brew` command](http://brew.sh/#install)
  - [X] Read [the Homebrew Wiki](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme) to learn more about Homebrew
- [X] Using the `brew` command, install the following packages:
  - [X] `zsh`
  - [X] `git`
  - [X] `hub`
  - [X] `node`
- [x] Add the output of the following commands as comments on your _WIP Issue_:
  - [x] `which zsh && zsh --version`
  - [x] `which git && git --version`
  - [x] `which hub && hub --version`
  - [x] `which node && node --version`
- [x] Install the following (bonus if you use `brew`):
  - [x] [Google Chrome](http://google.com/chrome)
  - [x] [Dash](http://kapeli.com/dash)
  - [x] [Slack](http://www.slack.com)
  - [x] [Atom](http://atom.io)
- [x] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  - [x] Add a link to your new Github repo as a comment on your _WIP Issue_
- [x] Create a new repository called `TIY-Assignments`
  - [x] Check the box to create an initial `README.md` file
  - [x] Select the `CC0` -- "Creative Commons" license for your work
  - [x] Add a link to your `TIY-Assignments` repo as a comment on your _WIP Issue_
- [x] [Complete the "Forking Projects" Github guide](https://guides.github.com/activities/forking/)
  - [x] Add a link to your `Fork-and-Spoon` repo as a comment on your _WIP Issue_
- [x] Install Prezto
  - [x] Find _and fork_ the Prezto project on Github; add a link as a comment on your _WIP Issue_
  - [x] Use the `hub` command to clone your fork into your home directory as `.zprezto`: `hub clone prezto .zprezto`
- [X] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
  - [X] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
  - [X] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)
### Deliverables:
- [x] _WIP Issue_
  - [x] named `00 -- Brace Yourself -- YOUR NAME`
  - [x] with description matching **Tasks**
- [x] A Github Profile with:
  - [x] Intelligible picture of yourself
  - [x] Your full name
  - [x] A valid email address
- [x] Comments on your _WIP Issue_ with output from
  - [x] `which zsh && zsh --version`
  - [x] `which git && git --version`
  - [x] `which hub && hub --version`
  - [x] `which node && node --version`
- [x] Comments on your _WIP Issue_ with links to your repos for
  - [x] `Hello-World`
  - [x] `TIY-Assignments`
  - [x] `Fork-and-Spoon`
  - [x] `prezto`

**Comment by kmattiko** [comment]
zsh 5.0.7 (x86_64-apple-darwin14.0.0)

git version 2.3.2 (Apple Git-55)

git version 2.3.6 
hub version 2.2.1

v0.12.2

**Comment by kmattiko** [comment]
hello-world
https://github.com/kmattiko/hello-world

**Comment by kmattiko** [comment]
TIY-Assignments
https://github.com/kmattiko/TIY-Assignments

**Comment by kmattiko** [comment]
Fork-and-Spoon
https://github.com/kmattiko/Spoon-Knife

**Comment by kmattiko** [comment]
Prezto
https://github.com/kmattiko/prezto

**Comment by al-the-x** [comment]
Great job overall. You seem to have missed the Pull Request on the "Forking Projects" guide. Having practice with PRs is invaluable.

**Comment by al-the-x** [comment]
Please review and close... And accept the invitation to the team so that I can assign these issues to you in future. Thanks.
