### ISSUE TITLE
04--todo-cli1 Part 2--Jorge Hernandez

### ISSUE THREAD

**Issue by jorgehjr84** [TheIronYard--Orlando/2015--SUMMER--FEE#62]
- **Yak Shaving**
  - _WIP Issue:_ `04 -- TodoCLI, Part 2 -- YOUR NAME`
  - _WIP Branch:_
    - `USERNAME.github.io:04--todo-cli-2`
    - `TIY-Assignments:04--todo-cli-2`
  - _WIP Files:_
    - `USERNAME.github.io`
      - `about/javascript.md`
    - `TIY-Assignments`
      - `todos.js`
      - `string-calculator.js`
      - `check-writing.js`
- **Reading JavaScript**
  - [x] `{ }` as block operator
  - [x] `if`, `else`, `switch`
  - [ ] `try/catch`, `throw`
  - [x] `for`, `while`, `do-while`
- **Todo CLI, Part 2**
  - [x] checkpoint from end of class
  - [x] added 1 new (failing) test!
  - [x] passing tests again!
  - [x] added 1 new feature!
  - [ ] **BEAST MODE** API Complete!
  - [ ] **NIGHTMARE MODE** Feature complete!
- **Coding Katas**
  - **String Calculator**
    - [x] function `toNumber` exists!
    - [x] `toNumber("zero")` works!
    - [x] function `add` exists!
    - [x] `add("zero", "zero")` works!
    - [x] `"one"` plus `"one"` is `2`!
    - [x] `"two"` plus `"two"` is `4`!
    - [ ] make `"seven"` up yours!
    - [x] and `"nine"` is the end!
  - [x] First pair!
  - [x] Second pair!
  - [ ] Third pair!

**Comment by jorgehjr84** [comment]
https://github.com/jorgehjr84/TIY-Assignments/pull/8

**Comment by al-the-x** [comment]
I know you've completed the journaling exercise from looking at your previous PR, but I need a link to _each_ active PR in your _WIP Issue_. Also, you should have paired with _three different folks_ on the TDD assignment. I only see two checked off and one credited in your commit messages.

**Comment by al-the-x** [comment]
Please review and close.

**Comment by jorgehjr84** [comment]
Thanks, I actually only was able to pair with Sean and Ben. However when I paired with Ben we got distracted with the division by zero problem.
